{ pkgs, config, osConfig, lib, ... }:
with lib;
{
  config = mkIf (osConfig.features.wms.wm == "hyprland") {
    home.file.".config/hypr" = {
      source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.dotfiles/hyprland/.config/hypr";
      recursive = true;
    };

    # pick whether to use hy3 plugin layout or builtin dwindle
    home.file.".config/hypr-nix-additions.conf".text = ''
      # === This file is generated by Home-Manager ===
      # === This sets dynamic values for differnt context depends on the host ===
      # === Such as picking hyprland tiling layout or monitor resolutions and different display handling ===

    '' + (if osConfig.networking.hostName == "parthGalen" then ''
      source = ~/.config/hypr/laptop.conf
    '' else if osConfig.networking.hostName == "dorthonion" then ''
      source = ~/.config/hypr/pc.conf
    '' else "") + (if osConfig.features.wms.hyprland.hy3.enable then ''
      plugin {
        plugin = ${pkgs.hyprlandPlugins.hy3}/lib/libhy3.so
      }
      source = ~/.config/hypr/hy3.conf
    '' else ''
      source = ~/.config/hypr/dwindle.conf
    '');


    features.wms.wayland.launchParams = [
      # to be able to share ~/bin/ dir to run sessions script
      "export PATH=\"$HOME/bin:$PATH\""

      "exec Hyprland" 
    ];
  };
}
